"""
Seed Events — high-quality manually curated events (2025-2026).
These are REAL events from research, used as fallback/bootstrap data.
The agent always has something to show even before API keys are configured.
"""
from typing import List
from models.event import EventCreate
from ingestion.base_connector import BaseConnector
from loguru import logger


SEED_DATA = [
    # ─── Asia / Singapore ──────────────────────────────────
    {
        "name": "Asia Tech x Singapore 2026 (ATxSG)",
        "description": "Asia's flagship tech event. ATxEnterprise covers enterprise tech, AI, telecom, digital infrastructure, satellite, start-ups and enterprise solutions. ATxSummit is the apex policy/leadership layer with 1,200+ VIPs from 110+ countries.",
        "start_date": "2026-05-20", "end_date": "2026-05-22",
        "venue_name": "Singapore EXPO + Capella Singapore",
        "city": "Singapore", "country": "Singapore",
        "est_attendees": 22000, "vip_count": 1200,
        "category": "tech",
        "industry_tags": "enterprise technology,AI,telecom,cloud,digital infrastructure,data",
        "audience_personas": "CIO,CTO,CDO,Head of AI,Head of Data,digital transformation leader,enterprise tech buyer,investor",
        "ticket_price_usd": 0.0, "price_description": "Free visitor pass; SGD 280 buyer pass; SGD 815 premium",
        "registration_url": "https://asiatechxsg.com/",
        "sponsors": "Google, Microsoft, AWS, Singtel",
        "speakers_url": "https://asiatechxsg.com/speakers",
        "agenda_url": "https://asiatechxsg.com/agenda",
        "edition_number": "Annual flagship",
        "source_url": "https://asiatechxsg.com/",
    },
    {
        "name": "Smart Health Asia 2026",
        "description": "Digital health trade show focused on AI, telemedicine, healthtech, healthcare innovation, digital transformation in care delivery. 300+ qualified buyers, 120+ speakers, 100+ sessions.",
        "start_date": "2026-07-01", "end_date": "2026-07-02",
        "venue_name": "Sands Expo & Convention Centre",
        "city": "Singapore", "country": "Singapore",
        "est_attendees": 5000, "vip_count": 300,
        "category": "healthcare",
        "industry_tags": "digital health,medtech,AI in healthcare,telemedicine,healthtech",
        "audience_personas": "Hospital CIO,Hospital CDO,healthcare provider,policymaker,regulator,payer,digital health leader,investor",
        "ticket_price_usd": 199.0, "price_description": "USD 199 general; some categories free; exhibitor from USD 990",
        "registration_url": "https://smarthealthasia.com/",
        "speakers_url": "https://smarthealthasia.com/speakers",
        "agenda_url": "https://smarthealthasia.com/agenda",
        "source_url": "https://smarthealthasia.com/",
    },
    {
        "name": "CeMAT Southeast Asia 2026",
        "description": "Trade show for intralogistics, robotics, automation, warehousing, supply chain management and materials handling. Includes Knowledge Theatre and show-floor demos.",
        "start_date": "2026-05-12", "end_date": "2026-05-14",
        "venue_name": "Singapore EXPO",
        "city": "Singapore", "country": "Singapore",
        "est_attendees": 4500,
        "category": "logistics",
        "industry_tags": "intralogistics,warehousing,robotics,automation,supply chain,manufacturing",
        "audience_personas": "supply chain head,warehousing leader,operations leader,logistics tech buyer,manufacturing transformation",
        "ticket_price_usd": 0.0, "price_description": "Free visitor access; exhibitor/sponsor pricing on request",
        "registration_url": "https://cemat-sea.com/",
        "source_url": "https://cemat-sea.com/",
    },
    {
        "name": "The Asian Banker Summit 2026",
        "description": "BFSI leadership summit with tracks on AI, data, cloud, cyber, transaction finance, cross-border finance, risk and digital banking.",
        "start_date": "2026-05-13", "end_date": "2026-05-14",
        "venue_name": "Mandarin Oriental Kuala Lumpur",
        "city": "Kuala Lumpur", "country": "Malaysia",
        "est_attendees": 1000,
        "category": "finance",
        "industry_tags": "banking,fintech,financial services,digital banking,risk,compliance,data,AI",
        "audience_personas": "Bank CIO,Bank CTO,Head of Data,Head of Analytics,digital banking leader,risk head,compliance head,fintech decision maker",
        "ticket_price_usd": 1800.0, "price_description": "USD 1,800 for financial institutions; USD 2,800 for others",
        "registration_url": "https://asianbanker.com/summit2026/",
        "source_url": "https://asianbanker.com/summit2026/",
    },
    # ─── India ─────────────────────────────────────────────
    {
        "name": "DCD Connect India 2026",
        "description": "Inaugural India edition of the global DCD Connect series. Brings together 1,500+ senior digital infrastructure professionals, 60+ exhibitors, and 120+ expert speakers. DCD draws on 25+ years of global event experience.",
        "start_date": "2026-10-13", "end_date": "2026-10-14",
        "venue_name": "Fairmont Mumbai",
        "city": "Mumbai", "country": "India",
        "est_attendees": 1500, "exhibitor_count": 60, "speaker_count": 120,
        "category": "tech",
        "industry_tags": "data center,digital infrastructure,cloud,colocation,hyperscaler,IT infrastructure",
        "audience_personas": "CIO,CTO,IT infrastructure head,data center owner,DC operations leader,hyperscaler,investor",
        "ticket_price_usd": 0.0, "price_description": "See DCD website",
        "registration_url": "https://datacenterdynamics.com/events/dcd-connect-india-2026/",
        "edition_number": "Inaugural India edition (global series: 25+ years)",
        "source_url": "https://datacenterdynamics.com/events/dcd-connect-india-2026/",
    },
    {
        "name": "Chennai Cloud & Datacenter Convention 2026",
        "description": "Pure-play cloud and data center event with senior buyer concentration. 1,000+ senior IT and DC professionals, 70% C-level, directors, and DC owners.",
        "start_date": "2026-05-21", "end_date": "2026-05-21",
        "venue_name": "ITC Grand Chola",
        "city": "Chennai", "country": "India",
        "est_attendees": 1000, "vip_count": 700,
        "category": "tech",
        "industry_tags": "cloud,data center,IT infrastructure,digital transformation",
        "audience_personas": "CIO,CTO,IT director,data center owner,cloud architect,infrastructure head",
        "ticket_price_usd": 0.0, "price_description": "See website",
        "registration_url": "https://w.media/events/chennai-cloud-datacenter-convention-2026/",
        "edition_number": "3rd edition",
        "source_url": "https://w.media/events/chennai-cloud-datacenter-convention-2026/",
    },
    {
        "name": "25th Datacenter Summit & Awards 2026",
        "description": "Annual summit for CIOs, CTOs, IT infrastructure heads, and data center leaders. 300+ industry leaders expected.",
        "start_date": "2026-04-23", "end_date": "2026-04-23",
        "venue_name": "ITC Maratha Mumbai",
        "city": "Mumbai", "country": "India",
        "est_attendees": 300,
        "category": "tech",
        "industry_tags": "data center,IT infrastructure,cloud,awards",
        "audience_personas": "CIO,CTO,IT infrastructure head,data center leader",
        "ticket_price_usd": 0.0, "price_description": "See website",
        "registration_url": "https://ubsforums.com/datacenter-summit/",
        "edition_number": "25th edition",
        "source_url": "https://ubsforums.com/datacenter-summit/",
    },
    {
        "name": "Data Centre Conclave 2026",
        "description": "High-fit India data center event for focused 1-to-1 meetings. 200+ delegates, 50% CXO attendance. Participation from hyperscalers, operators, enterprises, infrastructure providers, and investors.",
        "start_date": "2026-07-24", "end_date": "2026-07-24",
        "venue_name": "Holiday Inn Mumbai",
        "city": "Mumbai", "country": "India",
        "est_attendees": 200, "vip_count": 100,
        "category": "tech",
        "industry_tags": "data center,infrastructure,hyperscaler,colocation",
        "audience_personas": "CXO,hyperscaler,infrastructure provider,enterprise IT,investor",
        "ticket_price_usd": 0.0, "price_description": "By invitation / registration",
        "registration_url": "https://nexgenconferences.com/",
        "edition_number": "3rd Annual",
        "source_url": "https://nexgenconferences.com/",
    },
    # ─── US Fleet / Transport ───────────────────────────────
    {
        "name": "TMC Annual Meeting 2026",
        "description": "The premier event for fleet maintenance professionals, OEM suppliers, and technology providers. Covers fleet technology trends, maintenance operations, telematics, connected vehicles.",
        "start_date": "2026-03-10", "end_date": "2026-03-13",
        "venue_name": "Nashville Convention Center",
        "city": "Nashville", "country": "USA",
        "est_attendees": 5000, "vip_count": 500,
        "category": "logistics",
        "industry_tags": "fleet maintenance,OEM,telematics,connected vehicles,transport tech",
        "audience_personas": "fleet maintenance leader,OEM,fleet ops director,service provider,tech integrator",
        "ticket_price_usd": 1200.0, "price_description": "Member/non-member rates; see ATA TMC website",
        "registration_url": "https://www.atabusinesssolutions.com/TMCSuperTech/",
        "source_url": "https://www.atabusinesssolutions.com/TMCSuperTech/",
    },
    {
        "name": "Fleet Forward Conference 2026",
        "description": "Emphasizes connected fleet solutions, EV fleet adoption, autonomous vehicles, and fleet management software. Strong C-suite buyer concentration.",
        "start_date": "2026-11-04", "end_date": "2026-11-06",
        "venue_name": "Monterey Conference Center",
        "city": "Monterey", "country": "USA",
        "est_attendees": 2000, "vip_count": 400,
        "category": "logistics",
        "industry_tags": "fleet management,connected fleet,EV,autonomous vehicles,telematics",
        "audience_personas": "fleet manager,tech integrator,fleet CTO,VP fleet operations",
        "ticket_price_usd": 1500.0, "price_description": "See Fleet Forward website",
        "registration_url": "https://www.fleetforward.com/",
        "source_url": "https://www.fleetforward.com/",
    },
    # ─── SAP / Enterprise Software ──────────────────────────
    {
        "name": "SAPinsider ERP Transformation Summit 2025",
        "description": "Deep SAP ERP transformation content for SAP professionals, end-user organizations, partners and vendors. Rich content on S/4HANA migration, cloud ERP, AI in SAP.",
        "start_date": "2025-10-22", "end_date": "2025-10-23",
        "venue_name": "Hyatt Regency New Orleans",
        "city": "New Orleans", "country": "USA",
        "est_attendees": 500, "est_buyer_orgs": 150,
        "category": "tech",
        "industry_tags": "SAP,ERP,S4HANA,cloud ERP,enterprise software,digital transformation",
        "audience_personas": "SAP admin,ERP project manager,CIO,IT director,SAP partner,RISE with SAP",
        "ticket_price_usd": 1200.0, "price_description": "Conference registration; see SAPinsider",
        "registration_url": "https://sapinsideronline.com/",
        "source_url": "https://sapinsideronline.com/",
    },
    # ─── Global / Cross-industry ───────────────────────────
    {
        "name": "World Economic Forum Annual Meeting 2026",
        "description": "Global forum for political and business leaders discussing the state of the world. Key themes: AI governance, geopolitics, sustainability, financial systems.",
        "start_date": "2026-01-20", "end_date": "2026-01-24",
        "venue_name": "Davos Congress Centre",
        "city": "Davos", "country": "Switzerland",
        "est_attendees": 3000, "vip_count": 3000,
        "category": "finance",
        "industry_tags": "global economy,AI governance,sustainability,finance,geopolitics",
        "audience_personas": "CEO,head of state,minister,central bank governor,global investor",
        "ticket_price_usd": 0.0, "price_description": "By invitation only",
        "registration_url": "https://www.weforum.org/events/",
        "source_url": "https://www.weforum.org/events/world-economic-forum-annual-meeting-2026/",
    },
    {
        "name": "Gartner IT Symposium/Xpo 2026",
        "description": "Premier conference for CIOs and IT executives. Topics: AI strategy, digital business, cybersecurity, cloud, data analytics, technology investments.",
        "start_date": "2026-10-19", "end_date": "2026-10-22",
        "venue_name": "Walt Disney World Swan and Dolphin",
        "city": "Orlando", "country": "USA",
        "est_attendees": 10000, "vip_count": 2000,
        "category": "tech",
        "industry_tags": "enterprise IT,AI strategy,cloud,cybersecurity,digital business,data",
        "audience_personas": "CIO,IT executive,CDO,CISO,VP Technology,digital transformation leader",
        "ticket_price_usd": 3995.0, "price_description": "From $3,995 per attendee",
        "registration_url": "https://www.gartner.com/en/conferences/na/symposium-us",
        "source_url": "https://www.gartner.com/en/conferences/na/symposium-us",
    },
    {
        "name": "Money20/20 USA 2026",
        "description": "World's largest fintech event. Covers payments, banking, lending, AI in finance, crypto, regulation, and financial infrastructure.",
        "start_date": "2026-10-25", "end_date": "2026-10-28",
        "venue_name": "The Venetian Las Vegas",
        "city": "Las Vegas", "country": "USA",
        "est_attendees": 13000, "vip_count": 2000,
        "category": "finance",
        "industry_tags": "fintech,payments,banking,AI in finance,crypto,regulation,lending",
        "audience_personas": "fintech founder,bank CTO,payments leader,CFO,venture capitalist,regulator",
        "ticket_price_usd": 3000.0, "price_description": "Various tiers; see Money20/20 website",
        "registration_url": "https://us.money2020.com/",
        "source_url": "https://us.money2020.com/",
    },
    {
        "name": "AWS re:Invent 2026",
        "description": "Amazon Web Services' annual cloud computing conference. 60,000+ cloud professionals, 3,000+ technical sessions, keynotes, workshops, and certification labs.",
        "start_date": "2026-11-30", "end_date": "2026-12-04",
        "venue_name": "Multiple Las Vegas venues",
        "city": "Las Vegas", "country": "USA",
        "est_attendees": 60000, "speaker_count": 2000,
        "category": "tech",
        "industry_tags": "cloud,AWS,DevOps,AI/ML,serverless,data,security,infrastructure",
        "audience_personas": "cloud architect,DevOps engineer,CTO,IT director,developer,startup CTO",
        "ticket_price_usd": 1799.0, "price_description": "From $1,799; virtual attendance available",
        "registration_url": "https://reinvent.awsevents.com/",
        "source_url": "https://reinvent.awsevents.com/",
    },
    {
        "name": "Microsoft Ignite 2026",
        "description": "Microsoft's flagship annual tech conference for IT professionals. Focus: Azure, Microsoft 365, Copilot/AI, security, developer tools, hybrid work.",
        "start_date": "2026-11-09", "end_date": "2026-11-13",
        "venue_name": "McCormick Place",
        "city": "Chicago", "country": "USA",
        "est_attendees": 30000, "speaker_count": 1000,
        "category": "tech",
        "industry_tags": "Microsoft,Azure,AI,cloud,security,developer,M365,Copilot",
        "audience_personas": "IT admin,cloud architect,developer,CTO,CIO,Microsoft partner",
        "ticket_price_usd": 2195.0, "price_description": "From $2,195; online free",
        "registration_url": "https://ignite.microsoft.com/",
        "source_url": "https://ignite.microsoft.com/",
    },
    {
        "name": "Google Cloud Next 2026",
        "description": "Google Cloud's annual developer and enterprise conference. Focus: AI, Gemini, data analytics, Kubernetes, security, and enterprise cloud migration.",
        "start_date": "2026-04-09", "end_date": "2026-04-11",
        "venue_name": "Mandalay Bay",
        "city": "Las Vegas", "country": "USA",
        "est_attendees": 25000,
        "category": "tech",
        "industry_tags": "Google Cloud,AI,Gemini,data analytics,Kubernetes,cloud,BigQuery",
        "audience_personas": "cloud developer,data engineer,CTO,startup founder,enterprise IT,ML engineer",
        "ticket_price_usd": 1299.0, "price_description": "From $1,299",
        "registration_url": "https://cloud.withgoogle.com/next",
        "source_url": "https://cloud.withgoogle.com/next",
    },
    {
        "name": "Salesforce Dreamforce 2026",
        "description": "World's largest software conference. CRM, AI, marketing automation, sales tech, service cloud, platform development.",
        "start_date": "2026-09-15", "end_date": "2026-09-18",
        "venue_name": "Moscone Center",
        "city": "San Francisco", "country": "USA",
        "est_attendees": 40000,
        "category": "tech",
        "industry_tags": "Salesforce,CRM,marketing automation,sales tech,AI,platform,low-code",
        "audience_personas": "Salesforce admin,sales director,marketing leader,CTO,ISV partner,developer",
        "ticket_price_usd": 1999.0, "price_description": "From $1,999; various categories",
        "registration_url": "https://www.salesforce.com/dreamforce/",
        "source_url": "https://www.salesforce.com/dreamforce/",
    },
    {
        "name": "Collision Conference 2026",
        "description": "North America's fastest-growing tech conference. Startup ecosystem, investors, enterprise tech, AI, future of work, climate tech.",
        "start_date": "2026-06-22", "end_date": "2026-06-25",
        "venue_name": "Enercare Centre",
        "city": "Toronto", "country": "Canada",
        "est_attendees": 40000, "vip_count": 3000,
        "category": "tech",
        "industry_tags": "startup,AI,VC,fintech,climate tech,enterprise,future of work",
        "audience_personas": "startup founder,VC investor,CTO,enterprise buyer,developer,journalist",
        "ticket_price_usd": 1199.0, "price_description": "From $1,199; startup discounts available",
        "registration_url": "https://collisionconf.com/",
        "source_url": "https://collisionconf.com/",
    },
    {
        "name": "Web Summit 2026",
        "description": "One of the world's largest tech conferences. Covers AI, startup funding, enterprise digital transformation, climate tech, policy, future of internet.",
        "start_date": "2026-11-02", "end_date": "2026-11-05",
        "venue_name": "Altice Arena",
        "city": "Lisbon", "country": "Portugal",
        "est_attendees": 70000, "vip_count": 5000,
        "category": "tech",
        "industry_tags": "AI,startup,enterprise tech,climate,policy,VC,SaaS,product",
        "audience_personas": "startup founder,CTO,investor,enterprise buyer,policy maker,developer",
        "ticket_price_usd": 1500.0, "price_description": "From €1,095 approx",
        "registration_url": "https://websummit.com/",
        "source_url": "https://websummit.com/",
    },
]


class SeedConnector(BaseConnector):
    name = "Seed"

    async def fetch(self) -> List[EventCreate]:
        events = []
        for d in SEED_DATA:
            name = d["name"]
            start = d["start_date"]
            city = d.get("city", "")
            events.append(EventCreate(
                id=self.make_id(),
                source_platform="Curated",
                source_url=d.get("source_url", ""),
                dedup_hash=self.make_hash(name, start, city),
                name=name,
                description=d.get("description", ""),
                short_summary=d.get("description", "")[:150],
                start_date=start,
                end_date=d.get("end_date", start),
                duration_days=1,
                venue_name=d.get("venue_name", ""),
                address="",
                city=city,
                country=d.get("country", ""),
                is_virtual=False,
                is_hybrid=False,
                est_attendees=d.get("est_attendees", 0),
                est_buyer_orgs=d.get("est_buyer_orgs", 0),
                vip_count=d.get("vip_count", 0),
                exhibitor_count=d.get("exhibitor_count", 0),
                speaker_count=d.get("speaker_count", 0),
                category=d.get("category", "tech"),
                industry_tags=d.get("industry_tags", ""),
                audience_personas=d.get("audience_personas", ""),
                ticket_price_usd=d.get("ticket_price_usd", 0.0),
                price_description=d.get("price_description", ""),
                registration_url=d.get("registration_url", ""),
                sponsors=d.get("sponsors", ""),
                speakers_url=d.get("speakers_url", ""),
                agenda_url=d.get("agenda_url", ""),
                edition_number=d.get("edition_number", ""),
            ))
        logger.info(f"Seed: loaded {len(events)} curated events.")
        return events
